In [1]:
import numpy as np

In [95]:
d1 = np.array([18, 22, 56, 1, 65, 12, 32, 10, 45, 78, 254])
d2 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])
d3 = np.array([[1, 2, 3, 4], [5, 1, 4, 5]])

In [17]:
d1

array([1, 2, 3, 4, 5, 1, 0, 0, 0, 1, 1])

In [18]:
d1.shape

(11,)

In [19]:
d2.shape

(2, 4)

In [21]:
d2.ndim

2

In [22]:
d1.dtype

dtype('int32')

In [25]:
result = d2 + d3
print(result)

[[2 2 3 4]
 [5 1 1 1]]


In [26]:
print(d1.sort)

<built-in method sort of numpy.ndarray object at 0x000001E84244B570>


In [29]:
print(d1)

[1 2 3 4 5 1 0 0 0 1 1]


In [32]:
np.sort(d1)

array([  1,  10,  12,  18,  22,  32,  45,  56,  65,  78, 254])

In [33]:
print(d1)

[ 18  22  56   1  65  12  32  10  45  78 254]


In [46]:
np.concatenate((d2, d3))

array([[1, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 2, 3, 4],
       [5, 1, 0, 0]])

In [41]:
d4 = np.zeros([5,5])
d4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
d5 = np.ones([8, 8])
d5

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [44]:
d1

array([ 18,  22,  56,   1,  65,  12,  32,  10,  45,  78, 254])

In [45]:
d6 = d1[1:6]
d6

array([22, 56,  1, 65, 12])

In [62]:
d7 = np.random.rand(5)
print(d7)
d10 = np.random.randint(0,108, size = 18)
print(np.sort(d10))

[0.52010513 0.23228785 0.59548367 0.58055651 0.79742105]
[0 0 2 4 4 4 5 5 5 6 6 6 7 7 8 8 9 9]


In [68]:
d8 = np.linspace(1, 4, 8, 1)
print(d8)

[1.         1.42857143 1.85714286 2.28571429 2.71428571 3.14285714
 3.57142857 4.        ]


In [69]:
d9 = np.arange(2, 12, 2)
print(d9)

[ 2  4  6  8 10]


In [80]:
print(d1[0])
print("\n")
print(d2)
print("\n")
print("d2[-1] : " ,d2[0,-1])

18


[[ 1  2  3  4]
 [ 8  9 10 11]]


d2[-1] :  4


In [88]:
print("1D array: d1:: \n----------\n",d1)
print("\n")
print("\n")
print("2D array: d2:: \n----------\n",d2)
print("\n")
print("d2[0:2 , 1:3] :: \n----------\n",d2[0:2 , 1:3])
print("\nd2[1: , :] :: \n----------\n",d2[1: , :])
print("\nd2[: , :] :: \n----------\n",d2[: , :])

1D array: d1:: 
----------
 [ 18  22  56   1  65  12  32  10  45  78 254]




2D array: d2:: 
----------
 [[ 1  2  3  4]
 [ 8  9 10 11]]


d2[0:2 , 1:3] :: 
----------
 [[ 2  3]
 [ 9 10]]

d2[1: , :] :: 
----------
 [[ 8  9 10 11]]

d2[: , :] :: 
----------
 [[ 1  2  3  4]
 [ 8  9 10 11]]


In [89]:
print(d2)
print(d3)

[[ 1  2  3  4]
 [ 8  9 10 11]]
[[1 2 3 4]
 [5 1 0 0]]


In [96]:
addition = d2 + d3
print("\naddition\n-------------\n", addition)

subtraction = d2 - d3
print("\nsubtraction\n-------------\n", subtraction)

multiplication = d2 * d3
print("\nmultilication\n-------------\n", multiplication)

division = (d2 / d3)
print("\ndivision\n-------------\n", division)


addition
-------------
 [[ 2  4  6  8]
 [13 10 14 16]]

subtraction
-------------
 [[0 0 0 0]
 [3 8 6 6]]

multilication
-------------
 [[ 1  4  9 16]
 [40  9 40 55]]

division
-------------
 [[1.  1.  1.  1. ]
 [1.6 9.  2.5 2.2]]


In [103]:
print(d2 [d2 < 5])
print("\n\n\n\n")
x = (d2 >= 5)
print(d2[x])
print("\n\n\n\n")
c = d2[(d2>2)&(d2<11)]
print(c)
print("\n\n\n\n")
f = (d2 > 5)|(d2 == 5)
print(f)

[1 2 3 4]





[ 8  9 10 11]





[ 3  4  8  9 10]





[[False False False False]
 [ True  True  True  True]]
